// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaCore.Data;

namespace PruebaCore.Migrations
{
    [DbContext(typeof(CatalogosDbContext))]
    [Migration("20190925044729_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaCore.EntityModels.CategoriaEntity", b =>
                {
                    b.Property<int>("Cat_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cat_Cat_Descripcion");

                    b.Property<int>("Cat_CodCategoria");

                    b.HasKey("Cat_ID");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("PruebaCore.EntityModels.SubCategoriaEntity", b =>
                {
                    b.Property<int>("SubCat_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SubCat_Cat_ID");

                    b.Property<string>("SubCat_Descripcion");

                    b.Property<int>("SubCat_SubCatCodigo");

                    b.HasKey("SubCat_ID");

                    b.HasIndex("SubCat_Cat_ID");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("PruebaCore.EntityModels.SubCategoriaEntity", b =>
                {
                    b.HasOne("PruebaCore.EntityModels.CategoriaEntity", "Categoria")
                        .WithMany("SubCategoria")
                        .HasForeignKey("SubCat_Cat_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
