// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaCore.Data;

namespace PruebaCore.Migrations.InventarioDb
{
    [DbContext(typeof(InventarioDbContext))]
    partial class InventarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaCore.EntityModels.ArticuloEntity", b =>
                {
                    b.Property<int>("Sku_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sku_Cantidad");

                    b.Property<int>("Sku_Cat_ID");

                    b.Property<string>("Sku_Codigo");

                    b.Property<string>("Sku_Descripcion");

                    b.Property<string>("Sku_Latitud");

                    b.Property<string>("Sku_Longitud");

                    b.Property<string>("Sku_NumeroSerie");

                    b.Property<int>("Sku_Sub_Cat_ID");

                    b.HasKey("Sku_ID");

                    b.ToTable("Articulo");
                });
#pragma warning restore 612, 618
        }
    }
}
